### ISSUE TITLE
App Crashes when initializing location provider

### ISSUE THREAD

**Issue by thoughtcastapp** [himbeles/LocationProvider#4]
Hi, I am trying to integrate location provider into my app...I added the swift package and I added the @ObservedObject and init code from the sample app to my main view in swiftui, and the plist entries as specified, and when I run my app I get this error:

2020-09-14 11:25:59.764437-0700 MyApp[24106:754941] *** Assertion failure in -[CLLocationManager setAllowsBackgroundLocationUpdates:], CLLocationManager.m:927
2020-09-14 11:25:59.767850-0700 MyApp[24106:754941] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: !stayUp || CLClientIsBackgroundable(internal->fClient) || _CFMZEnabled()'
*** First throw call stack:
(0x1944c9114 0x1a7c7fcb4 0x1943d8308 0x1956bc2c8 0x199fc94f8 0x104b7a9bc 0x104b7aad0 0x104b7a404 0x104984f7c 0x104a82328 0x19a95b2cc 0x104a81984 0x19ae737a0 0x104a81368 0x104a83414 0x19a925bdc 0x19abfb7ac 0x19abfb61c 0x19a946d8c 0x1ba6b6064 0x1ba6b6474 0x1ba6bf060 0x19aea7774 0x19aeaa448 0x19aea9044 0x19aeaa3e4 0x19aa368a8 0x19ae15054 0x19ae0db20 0x19aa334c8 0x19aeaa3c4 0x19aeab560 0x19aa50f78 0x19a7a8ec0 0x19a7a8e28 0x19a7a3ef4 0x1b7955f40 0x19a7a8e0c 0x19a7a8f40 0x194447ecc 0x1944425b0 0x194442af8 0x194442200 0x1aa4bc598 0x196d081b0 0x196d0d784 0x104b5ab4c 0x194121598)
libc++abi.dylib: terminating with uncaught exception of type NSException

Any ideas what might cause this?

**Comment by himbeles** [comment]
Hi, 

Have you added `Location` to `UIBackgroundModes` in the plist as described in the Readme? Seems like your app is not getting permission to run in the background. 

Alternatively, you can also tick the corresponding checkbox in the project settings. 

Please tell me if that resolved the issue. If not, you could you check if the linked minimal example project runs for you?

**Comment by thoughtcastapp** [comment]
That seemed to fix the crash (I hadn't had background services enabled, sorry for the lack of reading the readme heh)...for some reason my app doesn't require background services so I don't know if there is a granular way to disable the need for background services...

Now, I am having the same issue as the user in #3, here is my log for your reference:

`start() No location authorization status set by delegate yet. Try to start updates anyhow.
locationManager(_:didChangeAuthorization:) authorizedWhenInUse`

I have a swiftui view, and I am calling `locationProvider.requestAuthorization()` in my .onAppear method, but the authorization request pop up window isn't "popping up"...also, when i check for lat and lon via `locationProvider.location?.coordinate.latitude,` both come back nil...

**Comment by himbeles** [comment]
No worries...

- For setting different, more fine-grained properties, the easiest would be to just copy `LocationProvider.swift` into your project instead of using it as a package. It is only a single file anyhow. 
Then set `self.lm.allowsBackgroundLocationUpdates = false` in the `init()` function.

- For the problem with the popup not appearing: you can try deleting and reinstalling the app on Simulator/Device. There is sometimes problems with caching of old location permission settings when resetting the app permissions (background, etc.)

**Comment by thoughtcastapp** [comment]
Gotcha...yeah i deleted and reinstalled several times, but it seems like any time I call `locationManager.requestWhenInUserAuthorization()` it doesn't pop up the notification...

also any word on issue #3? seems to still be plaguing me as well...

**Comment by himbeles** [comment]
Would you mind running the minimal code example  

https://github.com/himbeles/LocationProviderExample

to see if that works for you?

Or share a minimum failing example of your code?

**Comment by himbeles** [comment]
Closed due to inactivity and missing feedback.

**Comment by jamestapping** [comment]
Hiya,

I want to use didChangeAuthorization and am a little confused about how to use it in conjunction with your implementation.
Do you have a code example please ?

Thanks
