### ISSUE TITLE
How to using on iOS14 WidgetKit

### ISSUE THREAD

**Issue by tommyz** [himbeles/LocationProvider#5]
Hi Hinbeles:
I want to use the LocationProvider, but it can't work on iOS14 WidgetKit.
Please you, make a sample project for iOS14 WidgetKit. Thank you.

**Comment by himbeles** [comment]
Hi, 
I have not tested usage with WidgetKit yet. 
I suggest you consider following the instructions here:
https://developer.apple.com/documentation/widgetkit/accessing-location-information-in-widgets
